# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kafka_message.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "Frame" do
    optional :raw_frame, :message, 1, "Frame.RawFrame"
    optional :t_created, :float, 2
    optional :t_updated, :float, 3
    repeated :objects, :string, 4
    repeated :faces, :bytes, 5
    repeated :matched_faces, :string, 6
  end
  add_message "Frame.RawFrame" do
    optional :movie_filename, :string, 1
    optional :movie_filepath, :string, 2
    optional :image_bytes, :bytes, 3
  end
end

Frame = Google::Protobuf::DescriptorPool.generated_pool.lookup("Frame").msgclass
Frame::RawFrame = Google::Protobuf::DescriptorPool.generated_pool.lookup("Frame.RawFrame").msgclass
