# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kafka_message.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kafka_message.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x13kafka_message.proto\"\xd9\x01\n\x05\x46rame\x12\"\n\traw_frame\x18\x01 \x01(\x0b\x32\x0f.Frame.RawFrame\x12\x11\n\tt_created\x18\x02 \x01(\x02\x12\x11\n\tt_updated\x18\x03 \x01(\x02\x12\x0f\n\x07objects\x18\x04 \x03(\t\x12\r\n\x05\x66\x61\x63\x65s\x18\x05 \x03(\x0c\x12\x15\n\rmatched_faces\x18\x06 \x03(\t\x1aO\n\x08RawFrame\x12\x16\n\x0emovie_filename\x18\x01 \x01(\t\x12\x16\n\x0emovie_filepath\x18\x02 \x01(\t\x12\x13\n\x0bimage_bytes\x18\x03 \x01(\x0c\x62\x06proto3')
)




_FRAME_RAWFRAME = _descriptor.Descriptor(
  name='RawFrame',
  full_name='Frame.RawFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='movie_filename', full_name='Frame.RawFrame.movie_filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='movie_filepath', full_name='Frame.RawFrame.movie_filepath', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='image_bytes', full_name='Frame.RawFrame.image_bytes', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=162,
  serialized_end=241,
)

_FRAME = _descriptor.Descriptor(
  name='Frame',
  full_name='Frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='raw_frame', full_name='Frame.raw_frame', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_created', full_name='Frame.t_created', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='t_updated', full_name='Frame.t_updated', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objects', full_name='Frame.objects', index=3,
      number=4, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='faces', full_name='Frame.faces', index=4,
      number=5, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='matched_faces', full_name='Frame.matched_faces', index=5,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_FRAME_RAWFRAME, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=241,
)

_FRAME_RAWFRAME.containing_type = _FRAME
_FRAME.fields_by_name['raw_frame'].message_type = _FRAME_RAWFRAME
DESCRIPTOR.message_types_by_name['Frame'] = _FRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Frame = _reflection.GeneratedProtocolMessageType('Frame', (_message.Message,), dict(

  RawFrame = _reflection.GeneratedProtocolMessageType('RawFrame', (_message.Message,), dict(
    DESCRIPTOR = _FRAME_RAWFRAME,
    __module__ = 'kafka_message_pb2'
    # @@protoc_insertion_point(class_scope:Frame.RawFrame)
    ))
  ,
  DESCRIPTOR = _FRAME,
  __module__ = 'kafka_message_pb2'
  # @@protoc_insertion_point(class_scope:Frame)
  ))
_sym_db.RegisterMessage(Frame)
_sym_db.RegisterMessage(Frame.RawFrame)


# @@protoc_insertion_point(module_scope)
