
#FROM digi0ps/python-opencv-dlib:latest
FROM spmallick/opencv-docker:opencv

ADD requirements_handcrafted.txt /usr/src/app/requirements_handcrafted.txt

RUN cd /usr/src/app \
    && pip3 install -r requirements_handcrafted.txt

CMD tail -f /dev/null

